Update en.json: Dreams translation
gimi-org/gimi-i18n pull request #573
Opened 2023-09-05 14:10 UTC by giminils

2023-09-05 15:28 UTC, callemannervik requested changes

2023-09-05 15:28 UTC, callemannervik commented on text_strings/client/en.json
> +  "pfs_take_over_offer_2_p5": "Enter the code "Gimi100" at sign in",
@giminils There is an issue here with the code, you need to use `“` instead of `"`

2023-09-06 05:58 UTC, gimi-anders commented on text_strings/client/en.json
> +  "pfs_take_over_offer_2_p5": "Enter the code "Gimi100" at sign in",
```suggestion
  "pfs_take_over_offer_2_p5": "Enter the code “Gimi100” at sign in",
```

2023-09-06 05:58 UTC, gimi-anders approved these changes

2023-09-06 07:55 UTC, merged