Family missions widget
gimi-org/gimi-i18n pull request #608
Opened 2023-09-28 13:06 UTC by MarySnopok

Texts for activation screen and string key change to meed new usage

2023-09-30 05:51 UTC, gimi-anders requested changes

2023-09-30 05:51 UTC, gimi-anders commented on text_strings/client/en.json
> +  "widget_description_family_missions": "Go through the basics of personal finances together with your child!",
Why changing the name of these keys? Aren't these flash cards showing any more?
Also, if the previous key names are in use, then we cannot merge this PR until we merge a `gimi-app` PR that fixes it.

2023-10-04 08:04 UTC, MarySnopok commented on text_strings/client/en.json
> +  "widget_description_family_missions": "Go through the basics of personal finances together with your child!",
@gimi-anders I renamed it cause it was used only within one card kidProfileParentFamilyMissions , which was an entry point for family missions and used only once. Now when we delete the Missions tab and family missions card we can/should rename the strings . I searched for these strings and flash card within repo, cant find any other usage. You can double check to be 100% sure.

2023-10-04 09:49 UTC, gimi-anders commented on text_strings/client/en.json
> +  "widget_description_family_missions": "Go through the basics of personal finances together with your child!",
The issue with renaming though is that we cannot merge this PR until we certainly know that the usage is removed/changed in the app.
For example, if I would have merged this PR yesterday, and today we make the release, obviously without changing the family missions code in the app. Then it means that the flash card would be missing the string.

2023-10-04 09:50 UTC, gimi-anders commented on text_strings/client/en.json
> +  "widget_description_family_missions": "Go through the basics of personal finances together with your child!",
Anyway, the release is branched out now, so it should be safe to merge this as long as the app code is updated before next release.

2023-10-04 09:50 UTC, gimi-anders approved these changes

2023-10-04 10:10 UTC, MarySnopok commented
@gimi-anders  Anyway I have conflicts to resolve. I can also revert back the old string and we will be on safe side. If it wont be used in future, then your clean up script will remove it. I will take it back

2023-10-04 11:51 UTC, gimi-anders approved these changes

2023-10-04 11:51 UTC, merged