Aggiemaster
gimi-org/gimi-i18n pull request #72
Opened 2022-02-28 16:57 UTC by Agata-Gimi

2022-03-01 12:18 UTC, brightbrained requested changes

2022-03-01 12:18 UTC, brightbrained commented on .husky/_/husky.sh
> +#!/bin/sh
This file/folder should be added to the gitignore. I can fix that for you.

2022-03-01 13:38 UTC, gimi-anders commented on .husky/_/husky.sh
> +#!/bin/sh
It is already in gitignore

2022-03-02 06:04 UTC, gimi-anders commented on .husky/_/husky.sh
> +#!/bin/sh
I have now removed the file from this PR

2022-03-02 06:05 UTC, gimi-anders submitted a review, later dismissed

2022-03-03 09:20 UTC, callemannervik approved these changes

2022-03-04 07:03 UTC, brightbrained approved these changes

2022-03-04 07:03 UTC, merged